### ISSUE TITLE
have a question

### ISSUE THREAD

**Issue by astrary** [NotHyper-474/CodeStage-ObscuredPrefs-Decrypter#1]
how can i use this for android games?

**Comment by NotHyper-474** [comment]
Good question. I actually made this only thinking on PCs so I really don't know how to answer that, but I believe you can use version [v0.1](https://github.com/NotHyper-474/CodeStage-ObscuredPrefs-Decrypter/releases/tag/0.1.0-alpha) (although I need to update it)  to be able to edit the PlayerPrefs in the file `/data/data/pkg-name/shared_prefs/pkg-name.xml` (pkg-name should be replaced with the app's package name)
![image](https://user-images.githubusercontent.com/40342021/197364914-e7605825-7ed3-453a-aacd-829c2159c23f.png)

**Comment by astrary** [comment]
Thanks!
